Cosmetic whitespace. Tabs should always render as 8 spaces
If you want 4 spaces, put 4 spaces :)

diff --git a/docker/alpine-php7-Dockerfile b/docker/alpine-php7-Dockerfile
--- a/docker/alpine-php7-Dockerfile
+++ b/docker/alpine-php7-Dockerfile
@@ -3,41 +3,41 @@ FROM alpine:3.8
 # dependencies required for running "phpize"
 # these get automatically installed and removed by "docker-php-ext-*" (unless they're already installed)
 ENV PHPIZE_DEPS \
-		autoconf \
-		dpkg-dev dpkg \
-		file \
-		g++ \
-		gcc \
-		libc-dev \
-		make \
-		pkgconf \
-		re2c
+        autoconf \
+        dpkg-dev dpkg \
+        file \
+        g++ \
+        gcc \
+        libc-dev \
+        make \
+        pkgconf \
+        re2c
 
 # persistent / runtime deps
 RUN apk add --no-cache --virtual .persistent-deps \
     apache2 \
-		ca-certificates \
-		curl \
+        ca-certificates \
+        curl \
     mysql-client \
-		tar \
+        tar \
     vim \
-		xz \
+        xz \
 # https://github.com/docker-library/php/issues/494
-		libressl
+        libressl
 
 # ensure www-data user exists, 82 is the standard uid/gid for "www-data" in Alpine
 RUN set -x \
-	&& addgroup -g 82 -S www-data \
-	&& adduser -u 82 -D -S -G www-data www-data
+    && addgroup -g 82 -S www-data \
+    && adduser -u 82 -D -S -G www-data www-data
 
 ENV PHP_INI_DIR /usr/local/etc/php
 RUN set -eux; \
-	mkdir -p "$PHP_INI_DIR/conf.d"; \
+    mkdir -p "$PHP_INI_DIR/conf.d"; \
 # allow running as an arbitrary user (https://github.com/docker-library/php/issues/743)
-	[ ! -d /var/www/html ]; \
-	mkdir -p /var/www/html; \
-	chown www-data:www-data /var/www/html; \
-	chmod 777 /var/www/html
+    [ ! -d /var/www/html ]; \
+    mkdir -p /var/www/html; \
+    chown www-data:www-data /var/www/html; \
+    chmod 777 /var/www/html
 
 ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi
 
@@ -58,119 +58,119 @@ ENV PHP_URL="https://secure.php.net/get/php-7.2.15.tar.xz/from/this/mirror" PHP_
 ENV PHP_SHA256="75e90012faef700dffb29311f3d24fa25f1a5e0f70254a9b8d5c794e25e938ce" PHP_MD5=""
 
 RUN set -xe; \
-	\
-	apk add --no-cache --virtual .fetch-deps \
-		gnupg \
-		wget \
-	; \
-	\
-	mkdir -p /usr/src; \
-	cd /usr/src; \
-	\
-	wget -O php.tar.xz "$PHP_URL"; \
-	\
-	if [ -n "$PHP_SHA256" ]; then \
-		echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -; \
-	fi; \
-	if [ -n "$PHP_MD5" ]; then \
-		echo "$PHP_MD5 *php.tar.xz" | md5sum -c -; \
-	fi; \
-	\
-	if [ -n "$PHP_ASC_URL" ]; then \
-		wget -O php.tar.xz.asc "$PHP_ASC_URL"; \
-		export GNUPGHOME="$(mktemp -d)"; \
-		for key in $GPG_KEYS; do \
-			gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-		done; \
-		gpg --batch --verify php.tar.xz.asc php.tar.xz; \
-		command -v gpgconf > /dev/null && gpgconf --kill all; \
-		rm -rf "$GNUPGHOME"; \
-	fi; \
-	\
-	apk del .fetch-deps
+    \
+    apk add --no-cache --virtual .fetch-deps \
+        gnupg \
+        wget \
+    ; \
+    \
+    mkdir -p /usr/src; \
+    cd /usr/src; \
+    \
+    wget -O php.tar.xz "$PHP_URL"; \
+    \
+    if [ -n "$PHP_SHA256" ]; then \
+        echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -; \
+    fi; \
+    if [ -n "$PHP_MD5" ]; then \
+        echo "$PHP_MD5 *php.tar.xz" | md5sum -c -; \
+    fi; \
+    \
+    if [ -n "$PHP_ASC_URL" ]; then \
+        wget -O php.tar.xz.asc "$PHP_ASC_URL"; \
+        export GNUPGHOME="$(mktemp -d)"; \
+        for key in $GPG_KEYS; do \
+            gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+        done; \
+        gpg --batch --verify php.tar.xz.asc php.tar.xz; \
+        command -v gpgconf > /dev/null && gpgconf --kill all; \
+        rm -rf "$GNUPGHOME"; \
+    fi; \
+    \
+    apk del .fetch-deps
 
 COPY docker-php-source /usr/local/bin/
 
 RUN set -xe \
-	&& apk add --no-cache --virtual .build-deps \
-		$PHPIZE_DEPS \
-		argon2-dev \
-		coreutils \
-		curl-dev \
-		libedit-dev \
-		libsodium-dev \
-		libxml2-dev \
-		libressl-dev \
-		sqlite-dev \
-	\
-	&& export CFLAGS="$PHP_CFLAGS" \
-		CPPFLAGS="$PHP_CPPFLAGS" \
-		LDFLAGS="$PHP_LDFLAGS" \
-	&& docker-php-source extract \
-	&& cd /usr/src/php \
-	&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
-	&& ./configure \
-		--build="$gnuArch" \
-		--with-config-file-path="$PHP_INI_DIR" \
-		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
-		\
+    && apk add --no-cache --virtual .build-deps \
+        $PHPIZE_DEPS \
+        argon2-dev \
+        coreutils \
+        curl-dev \
+        libedit-dev \
+        libsodium-dev \
+        libxml2-dev \
+        libressl-dev \
+        sqlite-dev \
+    \
+    && export CFLAGS="$PHP_CFLAGS" \
+        CPPFLAGS="$PHP_CPPFLAGS" \
+        LDFLAGS="$PHP_LDFLAGS" \
+    && docker-php-source extract \
+    && cd /usr/src/php \
+    && gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
+    && ./configure \
+        --build="$gnuArch" \
+        --with-config-file-path="$PHP_INI_DIR" \
+        --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
+        \
 # make sure invalid --configure-flags are fatal errors intead of just warnings
-		--enable-option-checking=fatal \
-		\
+        --enable-option-checking=fatal \
+        \
 # https://github.com/docker-library/php/issues/439
-		--with-mhash \
-		\
+        --with-mhash \
+        \
 # --enable-ftp is included here because ftp_ssl_connect() needs ftp to be compiled statically (see https://github.com/docker-library/php/issues/236)
-		--enable-ftp \
+        --enable-ftp \
 # --enable-mbstring is included here because otherwise there's no way to get pecl to use it properly (see https://github.com/docker-library/php/issues/195)
-		--enable-mbstring \
+        --enable-mbstring \
 # add in mysql
-		--with-mysql \
+        --with-mysql \
 # add in pdo mysq
-		--with-pdo-mysql \
+        --with-pdo-mysql \
 # --enable-mysqlnd is included here because it's harder to compile after the fact than extensions are (since it's a plugin for several extensions, not an extension in itself)
-		--enable-mysqlnd \
+        --enable-mysqlnd \
 # https://wiki.php.net/rfc/argon2_password_hash (7.2+)
-		--with-password-argon2 \
+        --with-password-argon2 \
 # https://wiki.php.net/rfc/libsodium
-		--with-sodium=shared \
-		\
-		--with-curl \
-		--with-libedit \
-		--with-openssl \
-		--with-zlib \
-		\
+        --with-sodium=shared \
+        \
+        --with-curl \
+        --with-libedit \
+        --with-openssl \
+        --with-zlib \
+        \
 # bundled pcre does not support JIT on s390x
 # https://manpages.debian.org/stretch/libpcre3-dev/pcrejit.3.en.html#AVAILABILITY_OF_JIT_SUPPORT
-		$(test "$gnuArch" = 's390x-linux-gnu' && echo '--without-pcre-jit') \
-		\
-		$PHP_EXTRA_CONFIGURE_ARGS \
-	&& make -j "$(nproc)" \
-	&& find -type f -name '*.a' -delete \
-	&& make install \
-	&& { find /usr/local/bin /usr/local/sbin -type f -perm +0111 -exec strip --strip-all '{}' + || true; } \
-	&& make clean \
-	\
+        $(test "$gnuArch" = 's390x-linux-gnu' && echo '--without-pcre-jit') \
+        \
+        $PHP_EXTRA_CONFIGURE_ARGS \
+    && make -j "$(nproc)" \
+    && find -type f -name '*.a' -delete \
+    && make install \
+    && { find /usr/local/bin /usr/local/sbin -type f -perm +0111 -exec strip --strip-all '{}' + || true; } \
+    && make clean \
+    \
 # https://github.com/docker-library/php/issues/692 (copy default example "php.ini" files somewhere easily discoverable)
-	&& cp -v php.ini-* "$PHP_INI_DIR/" \
-	\
-	&& cd / \
-	&& docker-php-source delete \
-	\
-	&& runDeps="$( \
-		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
-			| tr ',' '\n' \
-			| sort -u \
-			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
-	)" \
-	&& apk add --no-cache --virtual .php-rundeps $runDeps \
-	\
-	&& apk del .build-deps \
-	\
+    && cp -v php.ini-* "$PHP_INI_DIR/" \
+    \
+    && cd / \
+    && docker-php-source delete \
+    \
+    && runDeps="$( \
+        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
+            | tr ',' '\n' \
+            | sort -u \
+            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+    )" \
+    && apk add --no-cache --virtual .php-rundeps $runDeps \
+    \
+    && apk del .build-deps \
+    \
 # https://github.com/docker-library/php/issues/443
-	&& pecl update-channels \
-	&& rm -rf /tmp/pear ~/.pearrc \
-  &&  /usr/local/bin/docker-php-ext-install -j$(nproc) mysqli pdo_mysql shmop
+    && pecl update-channels \
+    && rm -rf /tmp/pear ~/.pearrc \
+    && /usr/local/bin/docker-php-ext-install -j$(nproc) mysqli pdo_mysql shmop
 
 COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/
 
@@ -201,40 +201,40 @@ RUN rm /etc/apache2/sites-enabled/000-default.conf
 WORKDIR /var/www/html/config
 
 RUN set -ex \
-	&& cd /usr/local/etc \
-	&& if [ -d php-fpm.d ]; then \
-		# for some reason, upstream's php-fpm.conf.default has "include=NONE/etc/php-fpm.d/*.conf"
-		sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null; \
-		cp php-fpm.d/www.conf.default php-fpm.d/www.conf; \
-	else \
-		# PHP 5.x doesn't use "include=" by default, so we'll create our own simple config that mimics PHP 7+ for consistency
-		mkdir php-fpm.d; \
-		cp php-fpm.conf.default php-fpm.d/www.conf; \
-		{ \
-			echo '[global]'; \
-			echo 'include=etc/php-fpm.d/*.conf'; \
-		} | tee php-fpm.conf; \
-	fi \
-	&& { \
-		echo '[global]'; \
-		echo 'error_log = /proc/self/fd/2'; \
-		echo; \
-		echo '[www]'; \
-		echo '; if we send this to /proc/self/fd/1, it never appears'; \
-		echo 'access.log = /proc/self/fd/2'; \
-		echo; \
-		echo 'clear_env = no'; \
-		echo; \
-		echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
-		echo 'catch_workers_output = yes'; \
-	} | tee php-fpm.d/docker.conf \
-	&& { \
-		echo '[global]'; \
-		echo 'daemonize = no'; \
-		echo; \
-		echo '[www]'; \
-		echo 'listen = 9000'; \
-	} | tee php-fpm.d/zz-docker.conf
+    && cd /usr/local/etc \
+    && if [ -d php-fpm.d ]; then \
+        # for some reason, upstream's php-fpm.conf.default has "include=NONE/etc/php-fpm.d/*.conf"
+        sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null; \
+        cp php-fpm.d/www.conf.default php-fpm.d/www.conf; \
+    else \
+        # PHP 5.x doesn't use "include=" by default, so we'll create our own simple config that mimics PHP 7+ for consistency
+        mkdir php-fpm.d; \
+        cp php-fpm.conf.default php-fpm.d/www.conf; \
+        { \
+            echo '[global]'; \
+            echo 'include=etc/php-fpm.d/*.conf'; \
+        } | tee php-fpm.conf; \
+    fi \
+    && { \
+        echo '[global]'; \
+        echo 'error_log = /proc/self/fd/2'; \
+        echo; \
+        echo '[www]'; \
+        echo '; if we send this to /proc/self/fd/1, it never appears'; \
+        echo 'access.log = /proc/self/fd/2'; \
+        echo; \
+        echo 'clear_env = no'; \
+        echo; \
+        echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
+        echo 'catch_workers_output = yes'; \
+    } | tee php-fpm.d/docker.conf \
+    && { \
+        echo '[global]'; \
+        echo 'daemonize = no'; \
+        echo; \
+        echo '[www]'; \
+        echo 'listen = 9000'; \
+    } | tee php-fpm.d/zz-docker.conf
 
 EXPOSE 80 443
 CMD ["apache2-foreground"]
